export const SEND_CONTACT = "SEND_CONTACT"
export const GET_SEO = "GET_SEO"
export const GET_MAIN_APIS = "GET_MAIN_APIS"
export const GET_HOME_BLOGS = "GET_HOME_BLOGS"
export const GET_SOCIAL_LINKS = "GET_SOCIAL_LINKS"
